### PR TITLE
Add steps to activate shell and install Jupyter.

### PR DESCRIPTION
**Pull request by karmenlu**

### CODE REVIEW

**Comment by willb** [comment]
Thanks so much, Karmen!

It looks like we can make this work on Fedora 32 by changing the Pipfile (without needing to change the instructions or run `pipenv shell`, etc).  I had to remove the explicit Python version dependency (since this code should work with any reasonably modern Python 3) and make the pandas dependency version flexible.

Are you willing to test with this Pipfile?  If it works for you, we can update the PR and merge.

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
numpy = "==1.16.4"
pandas = "~=0.25.0"
altair = "==2.3.0"
vega = "==1.4.0"
jupyter = "*"
```

**Comment by karmenlu** [comment]
I deleted my Pipfile.lock, ran `pipenv install` with the new Pipfile, and it worked for me.

**Comment by willb** [comment]
Awesome!  If you're willing to update the PR with the old README and the new Pipfile, I'll merge it in (so you get credit for identifying the issue).

**Comment by willb** [comment]
Thank you!

**Pull request merged**
